/// <reference types="vitest/config" />
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    // Turns the app into an installable PWA — this is what makes "Add to
    // Home Screen" on Android produce a real full-screen app icon instead
    // of just a browser bookmark, and lets it keep working offline.
    // Icons referenced below are generated by `npm run generate-pwa-assets`
    // (see pwa-assets.config.ts) from public/hours-logo-source.png.
    VitePWA({
      registerType: 'autoUpdate',
      // TODO #14: used to list favicon.svg — the real logo is a raster export with no vector
      // version, so there's no standalone SVG file to precache anymore (see index.html's comment).
      includeAssets: ['favicon.ico'],
      manifest: {
        name: 'h_OURs',
        short_name: 'h_OURs',
        description: 'Trade skills and items with your community.',
        theme_color: '#16825a',
        background_color: '#fbf9ff',
        display: 'standalone',
        start_url: '/',
        scope: '/',
        icons: [
          { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Pre-caches the app shell (JS/CSS/HTML/icons) on install so the
        // app still opens without a network connection afterwards.
        globPatterns: ['**/*.{js,css,html,svg,png,ico}'],
      },
    }),
  ],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: './src/setupTests.ts',
  },
})
